### ISSUE TITLE
Make a frontend stack plan

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/client#1]
We need to decide what frontend stack we're using.  Are we going to use vanilla languages or are we going to use frameworks like Bootstrap or React?

**Comment by micahlt** [comment]
After discussion, looks like we'll be using Sass and ES6+ JavaScript, and maybe some jQuery.  We'll use [Parcel.js](https://parceljs.org) to bundle the application.  @Scratch-Client-4/frontend make sure you're familiar with these technologies!

**Comment by moeenio** [comment]
Well, I guess this is obsolete now we're using Vue.

**Comment by micahlt** [comment]
@locness3 True.  Someone want to summarize the stack here so we can close this again?

**Comment by moeenio** [comment]
There's still one thing not sure : do we keep with SCSS or do we switch to LESS? See discussion in #5

**Comment by micahlt** [comment]
@locness3 Hmm... okay, leaving this open for further discussion.

**Comment by moeenio** [comment]
@Scratch-Client-4/frontend Do we keep with SCSS or do we switch to LESS ?

**Comment by icarusinthewings** [comment]
@locness3 I know neither, but if you could point me to a nice course for SCSS (Besides Codecademy) then I would vote SCSS. I already know SCSS, but only a little bit.

**Comment by ethanhanderson** [comment]
@locness3 just from skimming the less homepage it seems extremely similar but somehow less appealing than SCSS.
I'll vote for SCSS but LESS is still fine with me

**Comment by VFDan** [comment]
I'd prefer Stylus, but any of those preprocessors are fine with me

**Comment by ethanhanderson** [comment]
I believe preprocessors like LESS and Stylus are all branches off Sass. So if we wanted to use the most common and developed preprocessor, we'd be best suited with Sass

**Comment by moeenio** [comment]
I prefer LESS tho, because it's not trying to reinvent the wheel (like SASS does with the SASS (not SCSS) syntax or their namespace system), it's more of a CSS expansion. And it is simpler IMO.

**Comment by moeenio** [comment]
> I already know SCSS, but only a little bit.

Well @ConvexPolygon, won't be hard switching to LESS if needed.

**Comment by VFDan** [comment]
@Hexsphere Actually, Stylus is a bit different; it is simpler, as you don't need semicolons or brackets; Pythonic CSS, if you will

**Comment by micahlt** [comment]
@VFDan bruh I can't deal with that

**Comment by moeenio** [comment]
hmm

**Comment by arwen-undomiel** [comment]
There is only so much I can learn in a short amount of time. I think our best option should be the most flexible.

**Comment by ethanhanderson** [comment]
@VFDan I haven't mentioned SCSS because that flavor of Sass does allow for brackets and semicolons. Stylus is very similar to SASS, not SCSS.

**Comment by ethanhanderson** [comment]
So far all I've seen are opinions on which preprocessor is better. I hopefully can shed some light on this discussion.

If we're going for a preprocessor that builds on and is very similar to CSS, then LESS is a perfect choice.

If we're trying to use a preprocessor that has it's own styling patterns and provides more features, we'll want to use Sass. While I'm on this topic, I think SCSS is best suited for trying to be as close to the CSS syntax as possible.

Finally, and I'm not sure what case to make for Stylus except it's good for people who want some Less or Sass/Scss features without using them as far as I can tell.

**Comment by moeenio** [comment]
I think most people here are more familiar with basic CSS, so we should go with LESS IMO.

**Comment by arwen-undomiel** [comment]
@locness3 Yes, I agree.

**Comment by micahlt** [comment]
@Scratch-Client-4/frontend I'm good with LESS if you guys are.  Decision?

**Comment by icarusinthewings** [comment]
Less I guess. I need a place to learn LESS tho.

**Comment by VFDan** [comment]
@micahlt I guess that's fine; I'm good with any CSS preproccessor

**Comment by arwen-undomiel** [comment]
As long as it is in the CSS realm, I can probably learn it.

**Comment by moeenio** [comment]
Well, I think we'll go with LESS then. Anyone OK?

**Comment by ghost** [comment]
@ConvexPolygon try w3schools, they should have a LESS tutorial

**Comment by moeenio** [comment]
They don't. The best way to learn it is its documentation, https://lesscss.org

**Comment by arwen-undomiel** [comment]
@locness3 okay, is that free?

**Comment by moeenio** [comment]
?

**Comment by arwen-undomiel** [comment]
Oh sorry, I misread. I thought it was a link to a code learning site. I don’t have a credit card so I didn’t want to pay money.

**Comment by moeenio** [comment]
Ok, that's fine. Yeah, I never spent money for learning coding too :)

**Comment by micahlt** [comment]
All right, marking this as closed.  We're using Vue and Less.  :+1: This does mean that the current version of the client will need to be restyled with Less.

**Comment by moeenio** [comment]
Will work on this :P
