### ISSUE TITLE
I have a small question

### ISSUE THREAD

**Issue by EternityScratch** [Scratch-Client-4/client#10]
What coding are you using in the dark mode files?

**Comment by micahlt** [comment]
What... coding?

**Comment by micahlt** [comment]
@EternityScratch are you referring to SCSS?

**Comment by EternityScratch** [comment]
nvm i figuered it out

**Comment by moeenio** [comment]
❓

**Comment by BonfireScratch** [comment]
@EternityScratch this is not Scratch, dude, you need to elaborate more...
