### ISSUE TITLE
Switching to another methodology

### ISSUE THREAD

**Issue by moeenio** [Scratch-Client-4/client#11]
The project uses the [BEM](https://getbem.com) CSS methodology, which makes classes follow a `block__element--modifier` pattern, where (quoting from the website):

- `block` "Encapsulates a standalone entity that is meaningful on its own. While blocks can be nested and interact with each other, semantically they remain equal; there is no precedence or hierarchy."
- `element` "[are] parts of a block and have no standalone meaning. Any element is semantically tied to its block."
- `modifier` "[are] flags on blocks or elements. Use them to change appearance, behavior or state."

Alternatives are :

- [SMACCSS](https://smaccss.com), which splits the CSS into categories : Base, Layout, Module, State, Theme
- [SUITCSS](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md), which uses both utilities and components
- [Atomic CSS](https://acss.io), which "like inline styles, offers single-purpose units of style, but applied via classes."
- [Object-Oriented CSS](https://github.com/stubbornella/oocss/wiki)

Do you prefer any other than BEM @Scratch-Client-4/frontend ?

**Comment by micahlt** [comment]
@locness3 Ah, sorry, thought @Hexsphere already stated this, but we're using BEM.

**Comment by moeenio** [comment]
ok

**Comment by moeenio** [comment]
Reopening so @Scratch-Client-4/frontend can suggest if they prefer something else

**Comment by VFDan** [comment]
Which one does Scratch use?

**Comment by moeenio** [comment]
I'm not sure, I feel it depends on the page (project page, other page, or page that is in the old "style").

But I'm not sure Scratch is a good example to follow IMO

**Comment by ethanhanderson** [comment]
@micahlt I was only suggesting tools that I used. I think once we're ready to start coding we should make sure everyone's on the same page as far as what frameworks, methodologies, and architectures we use

**Comment by micahlt** [comment]
@Hexsphere Ah, okay.  Gotcha.  I still support BEM, as it looks like it's the easiest to use and read.

**Comment by VFDan** [comment]
I think BEM would be the best.

**Comment by micahlt** [comment]
Haven't heard from anyone else- everyone good with closing this issue and staying with BEM?
