### ISSUE TITLE
Snap(snapcraft.io) build for linux users

### ISSUE THREAD

**Issue by icarusinthewings** [Scratch-Client-4/client#13]
We could easily bring support to linux users using snapcraft.io! It is very easy, and I'm publishing my own snap today. It's like a universal app store.

**Comment by moeenio** [comment]
This is going to be a website, thus I don't think a desktop app (if that's what you want to do) is needed

**Comment by micahlt** [comment]
@ConvexPolygon Snaps are for desktop apps- and though we could technically package SC4 using Electron, I don't think it's necessary.
