### ISSUE TITLE
What is this? (Reading messages)

### ISSUE THREAD

**Issue by icarusinthewings** [Scratch-Client-4/client#14]
Describe what this is please (@micahlt)

**Comment by Jemunm** [comment]
> Describe what this is please (@micahlt)

What do you mean?

**Comment by micahlt** [comment]
@ConvexPolygon Um what

**Comment by icarusinthewings** [comment]
this was in a note. What do you mean by this?

**Comment by micahlt** [comment]
@ConvexPolygon what are you talking about?

**Comment by Jemunm** [comment]
I’m confused too

**Comment by moeenio** [comment]
You want us to explain what's Reading messages? Please don't open an issue for this.
instead you can open a discussion in the everyone team.
