### ISSUE TITLE
Preprocessor variables may not be parsed inside of CSS variables

### ISSUE THREAD

**Issue by moeenio** [Scratch-Client-4/client#15]
[Parcel's importing doesn't parse SASS variables inside of CSS variables](https://github.com/parcel-bundler/parcel/issues/1165), so the output code which should be CSS contains SASS variables. And strangely, that works, at least for me, maybe because the browser is capable of reading SASS by itself, knowing that a sourcemap is created and linked to in the output CSS, which allows the browser to access the original SCSS files.

This should be fixed though, either using [the postcss workaround](https://github.com/parcel-bundler/parcel/issues/1165#issuecomment-391833454) mentioned in the issue if we're able to set it up, or by finding another workaround.
cc @Scratch-Client-4/frontend

**Comment by VFDan** [comment]
We may not be using SCSS: #1

**Comment by micahlt** [comment]
@locness3 Couldn't this effectively be solved by just not using SCSS vars in CSS vars?

**Comment by moeenio** [comment]
Well, SCSS variables are a feature we should use, but if we should not use them, well why not. And if we switch to LESS, the problem may not need solving.

**Comment by ethanhanderson** [comment]
@locness3 if we use the Vue CLI then we won't be using Parcel. An interesting side note, both Parcel and Vue's CLI use Webpack under the hood for HMR and building the files

**Comment by moeenio** [comment]
What are the advantages of vue-cli?

**Comment by ethanhanderson** [comment]
Most that you use the `node-sass` and `sass-loader` packages, with as far as I know Parcel doesn't. I could be wrong about Parcel... 😛

**Comment by micahlt** [comment]
@locness3 Since we're using LESS, should this issue be closed?

**Comment by moeenio** [comment]
We need to make sure the problem doesn't exist with LESS + parcel.

**Comment by micahlt** [comment]
@locness3 Hm... okay then.  In my opinion Less/Sass vars aren't really useful for us since we're already going to use CSS3 vars to support darkmode.

**Comment by moeenio** [comment]
Well, if we don't use them (preprocessor variables) for dark/light mode, we shouldn't use them at all.

**Comment by micahlt** [comment]
We've established that preprocessor variables can't be chabged inside a browser.  That's a big weakness that CSS vars fill, and I don't see why Less or Sass vars are better than CSS vars in the first place.

**Comment by moeenio** [comment]
You had used preprocessor variables along with CSS variables at first, but we'll stick with CSS vars then.

**Comment by micahlt** [comment]
All right then.  If you want you can close this issue.  :+1:
