### ISSUE TITLE
Could you upload more mockups?

### ISSUE THREAD

**Issue by grngxd** [Scratch-Client-4/client#23]
I'm trying to make a chrome extention with the design language

**Comment by micahlt** [comment]
@AyzansAlt All of the mockups can be seen on Scratch in Ekmand's Scratch Redesign project.

**Comment by grngxd** [comment]
vector or bitm?

**Comment by micahlt** [comment]
No idea - you'd have to check.

**Comment by moeenio** [comment]
Well, vector - figma is a vector-based design program

**Comment by grngxd** [comment]
YE S FIGMA OK TY

**Comment by grngxd** [comment]
**closed?**

**Comment by moeenio** [comment]
Yeah, closed; btw, I mentioned Figma but the designs are on our private team so stick with using Ekmand's Scratch project.
