### ISSUE TITLE
Url?

### ISSUE THREAD

**Issue by retronbv** [Scratch-Client-4/client#3]
What is the url to the client?

Thx,
Yoyitsm3m8

**Comment by moeenio** [comment]
The client doesn't seem to be hosted somewhere yet. If you'd like to build it for testing, you'll need to [install git](https://git-scm.com) and [node+npm](https://nodejs.org). Then, from a command prompt/terminal, run :
```
npm install
npm install http-server
npx sass scss/index.scss dist/index.css
```
Then edit this part of the index.html file :
```
<head>
  <meta charset="utf-8">
  <title>SC4 | Home</title>
  <link rel="stylesheet" type="text/css" href="https://at.alicdn.com/t/font_o5hd5vvqpoqiwwmi.css">
  <link rel="stylesheet" href="/scss/index.scss">
</head>
```
to :
```
<head>
  <meta charset="utf-8">
  <title>SC4 | Home</title>
  <link rel="stylesheet" type="text/css" href="https://at.alicdn.com/t/font_o5hd5vvqpoqiwwmi.css">
  <link rel="stylesheet" href="dist/index.css">
</head>
```
And finally, run:
```
npx http-server
```
Point at the URL shown and you'll have the frontend working.
Good luck 😅

**Comment by retronbv** [comment]
Ok............ that might take me a bit bc I run Linux on my chromebook!

**Comment by moeenio** [comment]
Alternatively, you could try setting all of this up via [Netlify](https://netlify.com) or a [CodeAnywhere](https://codeanywhere.com) Container.

**Comment by retronbv** [comment]
Ok. I’ll try that. XD

**Comment by retronbv** [comment]
With netifly it doesn’t look like the css works...

[https://mystifying-mestorf-cd5a24.netlify.com/](url)

**Comment by moeenio** [comment]
Yeah, you have to tell netlify to run the `npx sass` command in my comment, and make sure that the HTML file points to `dist/index.css`. I recommand doing a fork to edit the HTML, and deploying that fork to netlify. To tell it to run the command, set `Build command` in the netlify settings to it.

**Comment by retronbv** [comment]
Ok

**Comment by micahlt** [comment]
@YOYITsM3M8 @locness3 We've actually seen that [Parcel](https://parceljs.org) works best.  Instead, navigate into the repository's top directory and run this: 
```bash
npm install -g parcel
parcel index.html
```

**Comment by moeenio** [comment]
Yeah, I know, I didn't know you were using parcel at time of writing.

**Comment by micahlt** [comment]
@locness3 No prob :D

**Comment by micahlt** [comment]
@YOYITsM3M8 We finally deployed the alpha of the client online; you can find it at https://scratch-client-4.web.app/

**Comment by moeenio** [comment]
I would say pre-pre-alpha tho

**Comment by retronbv** [comment]
Ok
