### ISSUE TITLE
Add more to package.json

### ISSUE THREAD

**Issue by moeenio** [Scratch-Client-4/client#4]
I'd like to add more information to the package.json. What should I add for :
- Name
- Entry point
- Build command
- Version
- Author
- License

?

**Comment by moeenio** [comment]
cc @Scratch-Client-4/frontend

**Comment by micahlt** [comment]
In my opinion:

- Name: Scratch Client 4
- Entry point: HTML files can be entry points, right?  If so, let's do `index.html`
- Build command: `parcel build index.html`
- Version: 0.1.2
- Author: SC4 Team
- License: this needs to be a separate issue

**Comment by moeenio** [comment]
>     * Name: Scratch Client 4
I think name shouldn't have spaces and such.

>     * Build command: `parcel build index.html`
parcel should be added as dependency then

**Comment by micahlt** [comment]
Hmm... thought I already added Parcel, but yeah.  That's what we're using to build.  I thought name was fine with spaces, but nope.  Let's do `scratch-client-4`.

**Comment by moeenio** [comment]
okay ;)

**Comment by ethanhanderson** [comment]
@locness3 Just FYI, we're still working on designing, so coding isn't on the horizon for a while now
