### ISSUE TITLE
Travis?

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/client#6]
I think at some point we'll need to set up a CI addon or GitHub Action.  Anyone got any experience with Travis CI?  @Scratch-Client-4/everyone

**Comment by moeenio** [comment]
I got a little with GitHub Actions, but what do you want to use CI for? Testing, or deploying? We could deploy on Netlify.

**Comment by micahlt** [comment]
@locness3 probably deploying.  I haven't considered deployment options yet.

**Comment by moeenio** [comment]
Well, no need for a complex ci, just Netlify (or alternative) set up to run parcel build command

**Comment by Semisol** [comment]
@micahlt I have used GH Actions and Travis before.

**Comment by micahlt** [comment]
@locness3 Hmm... Netlify's pricing doesn't look good... possibly Heroku or Firebase Apps would be a better choice.

**Comment by Semisol** [comment]
@micahlt I can host the dev builds.

**Comment by micahlt** [comment]
Do you host your own servers?

**Comment by Semisol** [comment]
Yes.

**Comment by Semisol** [comment]
I can't IP-Expose them but I could use ngrok or a small Google Cloud machine to expose them to the public.

**Comment by micahlt** [comment]
Interesting. We could use a subdomain of mine (https://dev.sc4.micahlindley.com) to access it. I'm considering purchasing https://sc4.app/ (https://link.getmailspring.com/link/D5AF8DD8-C7CD-4ED1-9A54-77EAAF836EFF@getmailspring.com/0?redirect=https%3A%2F%2Fsc4.app%2F&recipient=cmVwbHkrQUczM0hLSzdOTEVYVFpRWElXVjdaSlY0VEJRM1hFVkJOSEhDSEJBVjZFQHJlcGx5LmdpdGh1Yi5jb20%3D) when we go live.

**Comment by Semisol** [comment]
Okay.

**Comment by moeenio** [comment]
> @locness3 Hmm... Netlify's pricing doesn't look good... possibly Heroku or Firebase Apps would be a better choice.

Netlify free is sufficient for most tasks tho.

**Comment by moeenio** [comment]
But yeah, firebase apps or heroku, or now.sh are good too

**Comment by arwen-undomiel** [comment]
I have used Netlify in the past, it's okay. We should look into other options as well.

**Comment by micahlt** [comment]
@locness3 @smileycreations15 @Mai-Trys I took some liberties and went ahead and deployed the alpha to Firebase: https://scratch-client-4.web.app/

**Comment by arwen-undomiel** [comment]
@micahlt Sounds good.

**Comment by ethanhanderson** [comment]
Some really quick comparison of hosting services similar to Now.sh (my personal preference) show that Netlify and Heroku are very similar in pricing.

If we were to use one of these services, it'd be easiest to simply have one of us to link the service to the main repository and then we'd be set.

Since all 3 of these services have continuous deployment, and Heroku and Now have git integration, we would need to make a development branch so we can choose what commits actually get deployed to the production site.

**Comment by moeenio** [comment]
> If we were to use one of these services, it'd be easiest to simply have one of us to link the service to the main repository and then we'd be set.

I guess this is the idea of using CI

**Comment by micahlt** [comment]
@Hexsphere and I have decided that manual deployment is the best option right now.  There's a possibility of moving to continuous deployment in the future, but currently to avoid having to set up another branch, a CI tool, and permissions, we're going to be manually deploying individual feature releases on Firebase.

**Comment by moeenio** [comment]
Why not deploy `master` via CI?

**Comment by moeenio** [comment]
At least for now
And what "permissions" do you mean?

**Comment by micahlt** [comment]
We'd have to re-host the client somewhere that supports integration such as Heroku but doesn't allow free custom domains like Firebase does.  We'd also have to set up a CI tool and make sure that only specific people could push to the `master` branch.

**Comment by moeenio** [comment]
If I'm not wrong, Netlify offers free custom domains, and it also sets up CI by itself when you connect the repository. As for permissions, I'm unsure how to do this.

**Comment by moeenio** [comment]
People here accepted the policies, so I think they won't push anything to master, and even if they do, it's not hard to revert a git commit (as soon as they don't force-push or whatever).
If you really want to protect access to the master branch, go to the repository's Settings > Branch protection > Add rule > set `master` as branch pattern > check Restrict who can push to matching rules and select people
