### ISSUE TITLE
Blockly Integration

### ISSUE THREAD

**Issue by MiniCoder11** [Scratch-Client-4/client#8]
The current Scratch 3.0 editor runs mainly off of Google's Blockly API. Are we going to also use Blockly for the custom editor or are we switching to a different block rendering solution?

I personally think it would be best if we stick with Blockly so that the interface and block dragging mechanics remain familiar for frequent users of Scratch. It's also far easier to implement than having to render all the blocks with custom SVG and canvas scripting.

Blockly is listed with the Apache 2.0 license which means we should have no issues using it. Also, will we eventually have seperate HTML and CSS files for the editor? I'd love to start working on it.

**Comment by ethanhanderson** [comment]
If you're willing to head up blocky development, that'd be great! Currently, there haven't any plans to go as far as building an editor into this project, as it was only intended to be a interactive demo of the original redesign.

**Comment by MiniCoder11** [comment]
Ah, okay. I thought that we were trying to create a functional third-party Scratch client for the people that aren't satisfied by the current website. I had no idea it was just a demo.

**Comment by ethanhanderson** [comment]
I think that making this project functional would be achievable with more backend developers, but right now I'm not sure what people are interested in working on. But yeah, right now we're just making this a interactive demo. 😛

**Comment by MiniCoder11** [comment]
Okay, that makes sense. If it helps, I could work backend, but I'm not sure if that would have any impact on anything.

**Comment by ethanhanderson** [comment]
Great! I'll add you to the backend team. :)

**Comment by MiniCoder11** [comment]
Yippee! Does this mean we can add at least partial Scratch functionality? (At least an editor. I wouldn't want to waste such a beautiful design concept 😄)

**Comment by ethanhanderson** [comment]
As far as I'm concerned, the closer we can get to Scratch the better :)

**Comment by MiniCoder11** [comment]
Okay! (I feel like people are judging me because I created a new GitHub account with my Scratch username to appear more relevant 😄 It looks like I'm a newbie.)

**Comment by ethanhanderson** [comment]
haha I don't think you're a newbie to any of this at all 😉

**Comment by MiniCoder11** [comment]
I guess my question has been answered. Permission to close this issue?

**Comment by ethanhanderson** [comment]
Of course :D

**Comment by moeenio** [comment]
> Ah, okay. I thought that we were trying to create a functional third-party Scratch client for the people that aren't satisfied by the current website. I had no idea it was just a demo.

The [Scratch client](https://github.com/LLK/scratch-www) and [Scratch editor](https://github.com/LLK/scratch-gui) are distinct things. We could incorporate the "official" editor into SC4 while keeping the custom client.

**Comment by micahlt** [comment]
@locness3 this is true.  @MiniCoder11 unfortunately, Scratch runs on a modified version of Blockly called [scratch-blocks](https://github.com/LLK/scratch-blocks).  And currently our priority is to be able to interact with the community- profile pages, loves and favorites, and project pages.  A custom editor is out of scope for now as it would require many different React components (which you can find on the LLK GitHub org) to be combined.  Plus, there were plans to use [Forkphorus](https://forkphorus.github.io) to render projects from there URLs.  If we build an editor, we couldn't use Forkphorus and would have to include the entire Scratch VM.  So let's just focus on the community right now.
